services:
  - type: web
    name: tourismbliss
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kerala_bliss.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kerala_bliss.settings
