# Generated by Django 5.2.1 on 2025-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('Munnar', 'Munnar'), ('Alleppey', 'Alleppey'), ('Wayanad', 'Wayanad')], default='Munnar', max_length=50),
        ),
    ]
