# Generated by Django 5.2.1 on 2025-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
